version: 'escribir_version_python_here'

services:
  web_service:
    build: 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - write_here_the_volumes
    ports:
      - write_the_port_here
    env_file:
      - write_env_file_name_here
    depends_on:
      - db_service
  db_service:
    image: postgres_image_for_db
    volumes:
      - write_here
    environment:
      - USER=write_your_user_here
      - PASSWORD=write_your_pass_here
      - DB=write_name_of_db_here
